name: Deploy Fullstack HR Management Optymum App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      FRONTEND_BUCKET: hr-management-optymum
      CLOUDFRONT_DISTRIBUTION_ID: E3ODSL8DJRDNJT
      EB_APP_NAME: HR-Management-Backend
      EB_ENV_NAME: HR-Management-Backend-env
      EB_BUCKET: elasticbeanstalk-us-east-1-654654387741
      KEEP_VERSIONS: 3 # Number of old versions to keep

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      # 3️⃣ Install AWS CLI
      - name: Setup AWS CLI
        run: |
          if command -v aws &> /dev/null; then
            echo "AWS CLI already installed, updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "Installing AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi
          aws --version

      # 4️⃣ Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      ###########################
      # Build & deploy frontend #
      ###########################
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          npm install -g npm@10.8.2
          npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Deploy Frontend to S3
        working-directory: ./frontend
        run: |
          aws s3 sync build s3://${{ env.FRONTEND_BUCKET }} --delete

      - name: Clean Old Frontend Files
        run: |
          # Keep only current deployment in S3 (frontend files are overwritten anyway)
          echo "Frontend files are automatically replaced during sync, no cleanup needed"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      ##########################
      # Build & deploy backend #
      ##########################
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install -g npm@10.8.2
          npm install -g @nestjs/cli
          npm ci --omit=dev
          
          # Install required type definitions as dev dependencies
          npm install --save-dev @types/cookie-parser @types/express @types/bcrypt @types/nodemailer
      
      - name: Build Backend
        working-directory: ./backend
        run: |
          # Fix environment variable typing issue
          sed -i "s/parseInt(process.env.DB_PORT, 10)/parseInt(process.env.DB_PORT || '5432', 10)/" src/app.module.ts
          npx nest build

      - name: Zip Backend for EB
        working-directory: ./backend
        run: |
          zip -r backend-deploy.zip * -x "node_modules/*" ".git/*" "*.env"

      - name: Upload Backend to S3 for EB
        working-directory: ./backend
        run: |
          VERSION_LABEL=${GITHUB_SHA::8}-$(date +%s)
          echo "VERSION_LABEL=$VERSION_LABEL" >> $GITHUB_ENV
          aws s3 cp backend-deploy.zip s3://${{ env.EB_BUCKET }}/backend-deploy-${VERSION_LABEL}.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ env.EB_APP_NAME }} \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=${{ env.EB_BUCKET }},S3Key=backend-deploy-${VERSION_LABEL}.zip

          aws elasticbeanstalk update-environment \
            --environment-name ${{ env.EB_ENV_NAME }} \
            --version-label $VERSION_LABEL

      - name: Clean Old Elastic Beanstalk Versions
        run: |
          # List all versions, sort by date, keep last KEEP_VERSIONS
          versions_to_delete=$(aws elasticbeanstalk describe-application-versions \
            --application-name ${{ env.EB_APP_NAME }} \
            --query 'ApplicationVersions[?VersionLabel!=`$VERSION_LABEL`].VersionLabel' \
            --output text | tr '\t' '\n' | sort | head -n -${{ env.KEEP_VERSIONS }})
          
          if [ -n "$versions_to_delete" ]; then
            echo "Deleting old versions:"
            echo "$versions_to_delete"
            for version in $versions_to_delete; do
              aws elasticbeanstalk delete-application-version \
                --application-name ${{ env.EB_APP_NAME }} \
                --version-label "$version" \
                --delete-source-bundle
            done
          else
            echo "No old versions to delete"
          fi

      - name: Clean Old S3 Deployment Files
        run: |
          # List all backend deployment zips, keep last KEEP_VERSIONS
          files_to_delete=$(aws s3api list-objects \
            --bucket ${{ env.EB_BUCKET }} \
            --prefix "backend-deploy-" \
            --query 'Contents[].Key' \
            --output text | tr '\t' '\n' | sort | head -n -${{ env.KEEP_VERSIONS }})
          
          if [ -n "$files_to_delete" ]; then
            echo "Deleting old deployment files:"
            echo "$files_to_delete"
            for file in $files_to_delete; do
              aws s3 rm "s3://${{ env.EB_BUCKET }}/$file"
            done
          else
            echo "No old deployment files to delete"
          fi
